### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by jarrah42** [cefriel/coney#1]
I've followed your instructions to start the coney docker containers, however when I go to the landing page, I see some issues with loading images. If I then click on "Create", I'm asked for a username/password. However nothing I type is accepted. See attached screenshots.

![Screen Shot 2021-05-10 at 5 30 19 PM](https://user-images.githubusercontent.com/6130694/117727163-ab88d380-b1b5-11eb-8810-49a7d11d9965.png)

![Screen Shot 2021-05-10 at 5 32 31 PM](https://user-images.githubusercontent.com/6130694/117727315-dc690880-b1b5-11eb-90e1-0541cc93b7fe.png)

**Comment by damiano-sca** [comment]
Hi @jarrah42!
Thank you for trying Coney and reporting this issue. It seems that there's an error in one of the environment files (the one in the 'Create' app). You can solve the issue by simply re-building the Coney Create app using the following command:

`sh coney.sh build create --env-cp`

This way, the wrong environment file will be replaced before the build with the correct one.
You can find more details about the coney.sh script in the README file.

Let us know if this fixes your issue.
Thanks!

**Comment by jarrah42** [comment]
That fixed it, thanks!
